### ISSUE TITLE
SWIG Issues due to enum classes

### ISSUE THREAD

**Issue by rainman110** [RISCSoftware/cpacs_tigl_gen#26]
Due to the most recent changes to enum classes from @bernhardmgruber,  SWIG produces code that cannot be compiled with VC 2015 anymore.

The issue is known at the swig issue tracker:
https://github.com/swig/swig/issues/675

Therefore, I suggest to go back to the "normal" enums.

__I am working on a PR!__

**Comment by bernhardmgruber** [comment]
This is sad to hear. But there were no troubles on the PR https://github.com/DLR-SC/tigl/pull/583. @rainman110 is SWIG not yet part of the CI?

**Comment by rainman110** [comment]
> @rainman110 is SWIG not yet part of the CI?

Unfortunately, this is not yet part of the CI. There need to be some adapations (e.g. shared OCC libs, pythonocc) and I never had the urge to implement it. But you are right, we should have the swig stuff as part of our CI process.
