### ISSUE TITLE
Enforce C++ 14 compiler

### ISSUE THREAD

**Issue by rainman110** [RISCSoftware/cpacs_tigl_gen#30]
The generator code uses some C++ 14 features. CMakeLists.txt enforces only C++ 11. 

Hence, the code will not compile on some machines. To fix this, just enforce C++ 14 in CMakeLists.txt.

**Comment by bernhardmgruber** [comment]
I believe this might result from some people working with CentOS 7 and relying on the system compiler, which only has partial support for C++14. I do not have such a system, maybe @RlanderRISCSW can check if a CMakelists.txt with CXX_STANDARD 14 still generates successfully.

**Comment by RlanderRISCSW** [comment]
CMake check for C++14 surprisingly works with gcc 4.8.5 (default on CentOS 7), so we have no problems when enforcing it.
