### ISSUE TITLE
Remove comments "// generated from /xsd:schema/xsd:complexType[XXX] "

### ISSUE THREAD

**Issue by rainman110** [RISCSoftware/cpacs_tigl_gen#35]
Although, this initially seemed to be a good idea, Pull Requests are often spammed with these kind of changes, which make it hard to identify the files that actually have changed.

Could we therefore remove these kind of comments?

**Comment by RlanderRISCSW** [comment]
You are right, I also recognized this problem during testing the integration of the fuselage kinks. I removed them.
