### ISSUE TITLE
Migrate from travis ci to free alternative

### ISSUE THREAD

**Issue by RlanderRISCSW** [RISCSoftware/cpacs_tigl_gen#39]
Travis CI seems to have discontinued the free version, so we need to search for an alternative

**Comment by bernhardmgruber** [comment]
GitHub actions work pretty well, are free, and include Linux, Windows and MacOS runners. You could give those a try.

**Comment by RlanderRISCSW** [comment]
> 
> 
> GitHub actions work pretty well, are free, and include Linux, Windows and MacOS runners. You could give those a try.

Thanks for the hint, I'll have a look at this. And nice to see that you are still following this project :-)

**Comment by RlanderRISCSW** [comment]
fixed via PR #49
