### ISSUE TITLE
How to link Boost library correctly?

### ISSUE THREAD

**Issue by MarAlder** [RISCSoftware/cpacs_tigl_gen#42]
Hi,

I would like to ask a question on the CMake boost integration. My approach is:
- get boost v1.75.0 from [here](https://www.boost.org/users/history/version_1_75_0.html)
- set `BOOST_ROOT` to this directory (i.e., `.../boost_1_75_0`)

CMake seems to find the correct version, but at the same time not...:
```
CMake Error at D:/Programme/QtCreator/Tools/CMake_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: system filesystem date_time regex
  unit_test_framework) (found version "1.75.0")
```
Am I using the correct builds or should `BOOST_ROOT` point to somewhere else?

**Comment by bernhardmgruber** [comment]
Have you tried turning static libraries off? That is, setting `Boost_USE_STATIC_LIBS` to `OFF`.

**Comment by MarAlder** [comment]
Thanks for the fast reply! Turning static libs off didn't help. However, the following approach solves the issue:

I followed https://github.com/BVLC/caffe/issues/6802#issuecomment-841066764 and built Boost according to [this tutorial](https://gist.github.com/sim642/29caef3cc8afaa273ce6) as I'm using MinGW under Windows. Now it compiled successfully 💪
