### ISSUE TITLE
Get aircraft/model element

### ISSUE THREAD

**Issue by MarAlder** [RISCSoftware/cpacs_tigl_gen#43]
Hi,

I'm generating classes for `cpacs/header/...` and `cpacs/vehicles/aircraft/model/reference/...` to use it for my cpacsLibrary project.

The first one is working fine in my test cases, e.g.:
```cpp
std::string name = m_cpacsTree->GetHeader().GetName();
```

However, I can't access the reference node. Is this the intended way to get an aircraft model?:

```cpp
auto model = m_cpacsTree->GetVehicles()->GetAircraft()->GetModels().at(0);
```

I guess the `unique_ptr` usage is not yet clear to me, as my (MinGW) compiler complains:

```
call to deleted constructor of 'std::unique_ptr<cpacsLib::generated::CPACSAircraftModel, std::default_delete<cpacsLib::generated::CPACSAircraftModel>>'
```

Until now my cpacsLibrary only has a dummy uID manager (just the function declarations, no content yet). But this should not be used at this point anyway, should it?

[generated.zip](https://github.com/RISCSoftware/cpacs_tigl_gen/files/7830202/generated.zip)

**Comment by RlanderRISCSW** [comment]
Hi,

The problem is that the variable `model` is of type `std::unique_ptr<CPACSAircraftModel>`, so a copy of the unique_ptr would be generated in the following line due to the assignment, which is not possible (would not be unique any more):
```cpp
auto model = m_cpacsTree->GetVehicles()->GetAircraft()->GetModels().at(0);
```
Instead of copying the unique_ptr you could take a reference to it by changing the code to:
```cpp
auto& model = m_cpacsTree->GetVehicles()->GetAircraft()->GetModels().at(0);
```
The uID manager is not relevant in this case.

**Comment by RlanderRISCSW** [comment]
Getting the reference-node via the `GetReference` function should be fine. The reference node is optional, thus the function returns a reference to the boost::optional type:
```cpp
        CPLIB_EXPORT virtual boost::optional<CPACSReference>& GetReference();
```
So accessing it could be written for example:
```cpp
const auto& reference = m_cpacsTree->GetVehicles()->GetAircraft()->GetModels().at(0)->GetReference();
if (reference) {
    const auto& point = reference->GetPoint();
}

**Comment by MarAlder** [comment]
Hmm, this is how I actually expected it to work. But my compiler is still not happy

```gdb
D:\Entwicklung\cpacsLibrary\src\tests\testLowLevel2.cpp:34: Fehler: invalid use of incomplete type 'class cpacsLib::generated::CPACSAircraftModel'
D:/Entwicklung/cpacsLibrary/src/tests/testLowLevel2.cpp: In member function 'virtual void lowLevelAPI2_doubleElements_Test::TestBody()':
D:/Entwicklung/cpacsLibrary/src/tests/testLowLevel2.cpp:34:89: error: invalid use of incomplete type 'class cpacsLib::generated::CPACSAircraftModel'
     const auto& reference = m_cpacsTree->GetVehicles()->GetAircraft()->GetModels().at(0)->GetReference();
                                                                                         ^~
```

and 

```gdb
D:\Entwicklung\cpacsLibrary\src\src\cpacsTree2\CPACSVehicles.h:24: In file included from D:/Entwicklung/cpacsLibrary/src/src/cpacsTree2/CPACSVehicles.h:24,
In file included from D:/Entwicklung/cpacsLibrary/src/src/cpacsTree2/CPACSVehicles.h:24,
                 from D:/Entwicklung/cpacsLibrary/src/src/cpacsTree2/CPACSCpacs.h:26,
                 from D:/Entwicklung/cpacsLibrary/src/src/api/cpacsLib.h:4,
                 from D:/Entwicklung/cpacsLibrary/src/tests/test.h:2,
                 from D:/Entwicklung/cpacsLibrary/src/tests/testLowLevel2.cpp:1:
D:/Entwicklung/cpacsLibrary/src/src/cpacsTree2/CPACSAircraft.h:33:11: note: forward declaration of 'class cpacsLib::generated::CPACSAircraftModel'
     class CPACSAircraftModel;
           ^~~~~~~~~~~~~~~~~~
```

I hope I didn't screw up something in CPACSGen with my modifications as it complains about some forward declaration issues.

**Comment by MarAlder** [comment]
Being happy about the answer and therefore closing the issue :)
