### ISSUE TITLE
Return XPath

### ISSUE THREAD

**Issue by MarAlder** [RISCSoftware/cpacs_tigl_gen#45]
Hi,

I propose to add a method which returns the current XPath. Something like:

```cpp
CPLIB_EXPORT virtual const std::string& GetXPath() const;
```

```cpp
const std::string& aeroMapType::GetXPath() const
    {
        return m_xPath;
    }
```

 `m_xPath` could be set in `ReadCPACS`. 

This could be useful information, e.g. to make aeroMaps selectable in a GUI:
![grafik](https://user-images.githubusercontent.com/43143741/149102424-07f22d58-28e0-44c1-878b-a27d7051c7a3.png)

What do you think? I could try to implement a first draft.

**Comment by MarAlder** [comment]
So a solution might look like dac589e. It's working in my own test cases, but I have not touched the generator test cases yet.

**Comment by bernhardmgruber** [comment]
I understand your use case, but unfortunately your implementation will break if you mutate the CPAS tree at runtime (e.g. removing an aeroMap and then asking for the xpath. To allow for mutation, you would constantly need to update xpaths. I think it's better to avoid this duplication of structure information and always build the xpath form the actual tree in memory.
