### ISSUE TITLE
XSD code documentation using CDATA causes error message

### ISSUE THREAD

**Issue by MarAlder** [RISCSoftware/cpacs_tigl_gen#46]
Hi,

CPACS 3.4 employs `CDATA` to improve the XSD documentation (see [sandcastle documentation](https://documentation.help/Sandcastle-MAML/65e7e30a-ba03-4e10-b1f2-763a613b6e27.htm)) by encapsulating XML snippets, e.g.:
```xml
<ddue:code language="XML" title="CPACS header">
    <![CDATA[
<cpacs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="pathToSchemaFile/cpacs_schema.xsd">                                            
    ]]>
</ddue:code>
```

![grafik](https://user-images.githubusercontent.com/43143741/149180276-768ad875-9bb8-476e-a04a-85d690ab1832.png)

This causes an `Error: Invalid XPath expression "..." Invalid Expression` when generating the code. I think it comes from [TiXI](https://github.com/DLR-SC/tixi/blob/bac618608e0cb186d745f4826a6495ef1f5a9349/src/tixiInternal.c#L331).

**Comment by RlanderRISCSW** [comment]
added support for cdata entries during schema parsing, error should be fixed now
