### ISSUE TITLE
Filesystem.cpp: "sort" no member of "std"

### ISSUE THREAD

**Issue by MarAlder** [RISCSoftware/cpacs_tigl_gen#53]
Compiling under Windows with MSVC 2022 amd64 returns:
```
[build] [...]\src\lib\Filesystem.cpp(86,8): error C2039: "sort" ist kein Member von "std". [C:\Workspace\Entwicklung\cpacsGen\git\build\libCPACSGen.vcxproj]
```

Works fine under Ubuntu with gpp, though.

Could be fixed by adding `#include <algorithm>` in `Filesystem.cpp`.

**Comment by bernhardmgruber** [comment]
Please provide a PR, I will gladly merge it! Thx for spotting this!
