### ISSUE TITLE
CPACSGen execution time too long

### ISSUE THREAD

**Issue by MarAlder** [RISCSoftware/cpacs_tigl_gen#55]
Hello,

I have compiled CPACSGen under Ubuntu 20.04 in WSL2 and run it with the latest master branch of TiGL. This takes me about 20 to 30 minutes. I haven't tested any other system yet, but it shouldn't take that long, should it?

**Comment by RlanderRISCSW** [comment]
Hi, I had a similar issue when using a self-built TIXI library on Windows. My guess is that it is somehow related to the external libraries used by TIXI (libxml2, libxslt, curl), but I did not find the time yet to analyze this in detail. I was able to avoid the problem by using the prebuilt TIXI library from github, which does not lead to the performance problems.

**Comment by MarAlder** [comment]
Yep, changing TiXI solved this issue. I first used the installation from github actons `sudo apt-get install -y libboost-all-dev libtixi3-dev cmake cmake-data` in my WSL2, but installing and using tixi3 via conda helped. Thanks!
